version: "2.1"
services:
  server:
    image: compilerserver
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  client:
    image: client
    networks:
      app_net:
        ipv4_address: 172.16.238.7
networks:
  app_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24